#### Instructions:  
1. Libraries allowed: **Python basic libraries, numpy, and pytorch.**
2. Show all outputs.
3. Submit jupyter notebook and a pdf export of the notebook. 
4. For practice examples, change variable name, shape, mathematical operations, nummerical values, tensor sizes etc. Be creative!


## Introduction
In this assignment, you will learn the basics of pytorch through practicing examples in pytorch tutorials and get familarrity with  some of the pytorch functions and classes required for building NN models.

### Basics
#### Q1 
#### a) Tensors 
Complete the pytorch tutorial at https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html. For each of the concepts presetned in the tutorial, create your own example, which should be different from the tutorial as much as possible.  You must change the tensor,  variable name, numbers/numerical values, and mathematical operations (e.g, replace sum with multiplication), dimesnions. For exmaple, instead of 2-dimensional tensor in the first example, you should create 3 or 4 dimensional tensors with its elements randomly selected.

Add as many cells below as needed.

In [2]:
import torch
# create a 3D tensor with random elements
data = [[[1, 2, 3],[4, 5, 6]],
[[7, 8, 9],[10, 11, 12]],
[[13, 14, 15],[16, 17, 18]]]
x_data = torch.tensor(data)

In [3]:
# create a tensor with all ones with the same shape as x_data
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")

Ones Tensor: 
 tensor([[[1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1]]]) 



In [4]:
#Create a tensor with random elements with the same shape as x_data
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")

Random Tensor: 
 tensor([[[0.5997, 0.7895, 0.4562],
         [0.9853, 0.7005, 0.9501]],

        [[0.7160, 0.6089, 0.9914],
         [0.4117, 0.0057, 0.6032]],

        [[0.2571, 0.8459, 0.2079],
         [0.3095, 0.6695, 0.1256]]]) 



In [5]:
# Create a 4D tensor with all zeros
shape = (2, 3, 2, 2)
zeros_tensor = torch.zeros(shape)
print(f"Zeros Tensor: \n {zeros_tensor}")


Zeros Tensor: 
 tensor([[[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]],


        [[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]]])


In [6]:
# Create a tensor with random elements with the given shape
rand_tensor = torch.rand((2, 3, 4))
print(rand_tensor)

tensor([[[0.1177, 0.8063, 0.1279, 0.9512],
         [0.4100, 0.1460, 0.9032, 0.9833],
         [0.5340, 0.7847, 0.5825, 0.5940]],

        [[0.0190, 0.2178, 0.9665, 0.1155],
         [0.2723, 0.9841, 0.2613, 0.1089],
         [0.1897, 0.6965, 0.3593, 0.1268]]])


In [7]:
#Create a tensor with all ones with the given shape
ones_tensor = torch.ones((2, 3, 4))
print(ones_tensor)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


In [9]:
#Add the two tensors element-wise
added_tensor = rand_tensor + ones_tensor
print(f"Added Tensor: \n {added_tensor}")


Added Tensor: 
 tensor([[[1.1177, 1.8063, 1.1279, 1.9512],
         [1.4100, 1.1460, 1.9032, 1.9833],
         [1.5340, 1.7847, 1.5825, 1.5940]],

        [[1.0190, 1.2178, 1.9665, 1.1155],
         [1.2723, 1.9841, 1.2613, 1.1089],
         [1.1897, 1.6965, 1.3593, 1.1268]]])


In [10]:
#Multiply the two tensors element-wise
multiplied_tensor = rand_tensor * ones_tensor
print(f"Multiplied Tensor: \n {multiplied_tensor}")

Multiplied Tensor: 
 tensor([[[0.1177, 0.8063, 0.1279, 0.9512],
         [0.4100, 0.1460, 0.9032, 0.9833],
         [0.5340, 0.7847, 0.5825, 0.5940]],

        [[0.0190, 0.2178, 0.9665, 0.1155],
         [0.2723, 0.9841, 0.2613, 0.1089],
         [0.1897, 0.6965, 0.3593, 0.1268]]])


In [11]:
#Compute the mean of the multiplied tensor
mean = multiplied_tensor.mean()
print(f"Mean of Multiplied Tensor: {mean}")

Mean of Multiplied Tensor: 0.46910563111305237


In [12]:
#Compute the sum of the multiplied tensor along the first dimension
sum_along_dim1 = multiplied_tensor.sum(dim=1)
print(f"Sum along the first dimension: \n {sum_along_dim1}")

Sum along the first dimension: 
 tensor([[1.0618, 1.7369, 1.6137, 2.5285],
        [0.4811, 1.8983, 1.5871, 0.3512]])


In [14]:
#Compute the matrix multiplication between two tensors
tensor1 = torch.randn(3, 4)
tensor2 = torch.randn(4, 5)
product_tensor = tensor1 @ tensor2
print(f"Product Tensor: \n {product_tensor}")

Product Tensor: 
 tensor([[ 1.0490e-04, -1.1265e+00, -7.1441e-02, -1.9555e+00,  3.6324e-02],
        [ 1.4590e+00,  2.0406e+00, -8.7784e-03,  2.5693e+00, -1.7473e-01],
        [-4.9755e-01, -2.0409e+00,  7.5529e-01, -3.8621e+00, -1.1091e-01]])


In [19]:
#Compute the dot product between two tensors
product_tensor = tensor1 @ tensor2
print(f"Product Tensor: \n {product_tensor}")


Product Tensor: 
 tensor([[ 1.0490e-04, -1.1265e+00, -7.1441e-02, -1.9555e+00,  3.6324e-02],
        [ 1.4590e+00,  2.0406e+00, -8.7784e-03,  2.5693e+00, -1.7473e-01],
        [-4.9755e-01, -2.0409e+00,  7.5529e-01, -3.8621e+00, -1.1091e-01]])


In [22]:
import torch

# create a 3x3x3x3 tensor with random elements
tensor1 = torch.rand(3, 3, 3, 3)

# element-wise product using tensor.mul()
z1 = tensor1.mul(tensor1)

# element-wise product using torch.mul()
z2 = torch.mul(tensor1, tensor1)

# create a 3x3x3x3 tensor with random elements
z3 = torch.rand_like(tensor1)

# element-wise product using torch.mul() and output to z3
torch.mul(tensor1, tensor1, out=z3)

# compute the element-wise square root of z1
z4 = torch.sqrt(z1)

# compute the element-wise power of 3 for z2
z5 = torch.pow(z2, 3)



In [23]:

# compute the maximum element value of tensor1
max_val = tensor1.max()

# compute the sum of all elements in tensor1
agg = tensor1.sum()

# convert tensor1 to a numpy array
tensor1_np = tensor1.numpy()

# add 5 to all elements of tensor1 using tensor.add_()
tensor1.add_(5)


tensor([[[[5.4378, 5.2899, 5.3430],
          [5.4081, 5.4640, 5.2783],
          [5.7193, 5.3239, 5.3723]],

         [[5.5903, 5.2122, 5.8019],
          [5.2346, 5.7640, 5.5927],
          [5.2256, 5.2791, 5.2803]],

         [[5.4287, 5.4690, 5.8147],
          [5.5843, 5.8274, 5.2403],
          [5.3743, 5.8171, 5.0110]]],


        [[[5.2207, 5.7178, 5.1221],
          [5.7569, 5.7423, 5.3963],
          [5.9858, 5.0556, 5.3526]],

         [[5.9046, 5.3615, 5.3391],
          [5.5855, 5.7856, 5.4015],
          [5.7710, 5.8275, 5.4688]],

         [[5.6909, 5.4496, 5.8762],
          [5.4129, 5.1584, 5.0500],
          [5.4859, 5.3173, 5.3099]]],


        [[[5.6783, 5.1087, 5.1088],
          [5.2577, 5.7161, 5.6641],
          [5.9160, 5.6178, 5.0914]],

         [[5.3041, 5.3488, 5.1778],
          [5.2199, 5.4690, 5.3737],
          [5.0102, 5.1359, 5.7874]],

         [[5.6017, 5.6009, 5.7265],
          [5.8412, 5.0191, 5.5170],
          [5.3706, 5.3349, 5.1821]]]])

In [24]:

# create a tensor of ones with shape (4, 4)
t = torch.ones(4, 4)

# convert t to a numpy array
n = t.numpy()

# add 2 to all elements of t using tensor.add_()
t.add_(2)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [25]:
# print the tensors and values
print(f"tensor1:\n{tensor1}\n")
print(f"z1:\n{z1}\n")
print(f"z2:\n{z2}\n")
print(f"z3:\n{z3}\n")
print(f"z4:\n{z4}\n")
print(f"z5:\n{z5}\n")
print(f"max_val:\n{max_val}\n")
print(f"agg:\n{agg}\n")
print(f"tensor1_np:\n{tensor1_np}\n")
print(f"t:\n{t}\n")
print(f"n:\n{n}\n")

tensor1:
tensor([[[[5.4378, 5.2899, 5.3430],
          [5.4081, 5.4640, 5.2783],
          [5.7193, 5.3239, 5.3723]],

         [[5.5903, 5.2122, 5.8019],
          [5.2346, 5.7640, 5.5927],
          [5.2256, 5.2791, 5.2803]],

         [[5.4287, 5.4690, 5.8147],
          [5.5843, 5.8274, 5.2403],
          [5.3743, 5.8171, 5.0110]]],


        [[[5.2207, 5.7178, 5.1221],
          [5.7569, 5.7423, 5.3963],
          [5.9858, 5.0556, 5.3526]],

         [[5.9046, 5.3615, 5.3391],
          [5.5855, 5.7856, 5.4015],
          [5.7710, 5.8275, 5.4688]],

         [[5.6909, 5.4496, 5.8762],
          [5.4129, 5.1584, 5.0500],
          [5.4859, 5.3173, 5.3099]]],


        [[[5.6783, 5.1087, 5.1088],
          [5.2577, 5.7161, 5.6641],
          [5.9160, 5.6178, 5.0914]],

         [[5.3041, 5.3488, 5.1778],
          [5.2199, 5.4690, 5.3737],
          [5.0102, 5.1359, 5.7874]],

         [[5.6017, 5.6009, 5.7265],
          [5.8412, 5.0191, 5.5170],
          [5.3706, 5.3349, 5.1821]]

#### b) Autormatic differentiation
Complete the tutorial at https://pytorch.org/tutorials/beginner/basics/autogradqs_tutorial.html . Again, make changes to the tensor, variable name etc. to make your example completely different from tutorial. Failing to do so will earn you zero credit.

Add as many cells below as needed.

In [28]:
# this is a simplest one-layer neural network, with input x1, parameters we and bi, and some loss function
# implemented in pytorch
# all the variables names, tensors are changed

import torch as t # replacing torch with easy letter

x1 = t.ones(3)  # input tensor #x
x0 = t.zeros(4)  # expected output #y

we = t.randn(3, 4, requires_grad=True) #w
bi = t.randn(4, requires_grad=True) #b

fun = t.matmul(x1, we)+bi #z
lossFunction = t.nn.functional.binary_cross_entropy_with_logits(fun, x0) # loss function


In [29]:
print(x1)

tensor([1., 1., 1.])


In [30]:
print(x0)

tensor([0., 0., 0., 0.])


In [31]:
print(we)

tensor([[-0.1804, -1.9022, -0.6872,  1.0594],
        [-0.7047, -2.0411, -1.4257,  0.9541],
        [-1.3367,  0.2772, -0.4925,  0.1066]], requires_grad=True)


In [32]:
print(bi)

tensor([ 0.6421, -1.2354,  1.1482, -0.3509], requires_grad=True)


In [33]:
print(fun)

tensor([-1.5798, -4.9015, -1.4572,  1.7692], grad_fn=<AddBackward0>)


In [34]:
print(lossFunction)

tensor(0.5827, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)


In [35]:
print(f"Gradient function for z = {fun.grad_fn}")
print(f"Gradient function for loss = {lossFunction.grad_fn}")

Gradient function for z = <AddBackward0 object at 0x7fc44aefd3a0>
Gradient function for loss = <BinaryCrossEntropyWithLogitsBackward0 object at 0x7fc44aefd850>


In [36]:
# computing gradient

In [37]:
lossFunction.backward(retain_graph=True)
print(we.grad)
print(bi.grad)


tensor([[0.0427, 0.0018, 0.0472, 0.2136],
        [0.0427, 0.0018, 0.0472, 0.2136],
        [0.0427, 0.0018, 0.0472, 0.2136]])
tensor([0.0427, 0.0018, 0.0472, 0.2136])


In [38]:
# disabling gradient tracking
fun = t.matmul(x1, we)+bi
print(fun.requires_grad)

with t.no_grad():
    fun = t.matmul(x1, we)+bi
print(fun.requires_grad)

True
False


In [39]:
# Tensor Gradients and Jacobian Products

In [40]:
input_tensor = t.eye(6, 5, requires_grad=True)
output_tensor = (input_tensor + 1).pow(2).t()
output_tensor.backward(t.ones_like(output_tensor), retain_graph=True)


print(f"First call\n{input_tensor.grad}")
output_tensor.backward(t.ones_like(output_tensor), retain_graph=True)

print(f"\nSecond call\n{input_tensor.grad}")
input_tensor.grad.zero_()

output_tensor.backward(t.ones_like(output_tensor), retain_graph=True)
print(f"\nCall after zeroing gradients\n{input_tensor.grad}")


First call
tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.],
        [2., 2., 2., 2., 4.],
        [2., 2., 2., 2., 2.]])

Second call
tensor([[8., 4., 4., 4., 4.],
        [4., 8., 4., 4., 4.],
        [4., 4., 8., 4., 4.],
        [4., 4., 4., 8., 4.],
        [4., 4., 4., 4., 8.],
        [4., 4., 4., 4., 4.]])

Call after zeroing gradients
tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.],
        [2., 2., 2., 2., 4.],
        [2., 2., 2., 2., 2.]])


#### c) Datasets and Dataloader 
Complete the tutorial at https://pytorch.org/tutorials/beginner/basics/data_tutorial.html . 

Add as many cells below as needed.

In [ ]:
# this tutorial 3 is based on loading data and manipulating it 

#### d) Transforms
Complete the tutorial at https://pytorch.org/tutorials/beginner/basics/transforms_tutorial.html . 

Add as many cells below as needed.

#### e) Build model
Complete the tutorial at https://pytorch.org/tutorials/beginner/basics/buildmodel_tutorial.html. 

Add as many cells below as needed.

#### f) Optimization loop
Complete the tutorial at https://pytorch.org/tutorials/beginner/basics/optimization_tutorial.html. 

Add as many cells below as needed.

#### f) Save, load, and use model
Complete the tutorial at https://pytorch.org/tutorials/beginner/basics/saveloadrun_tutorial.html. 

Add as many cells below as needed.

### Exercise
### Q2
#### a) 
Create a pytorch class for a neural network with 3 inputs, one hidden layer with 5 neurons and ReLU activatioin function, one output layer with 2 outputs. Use $torch.nn.init$ to initialize the biases to zeros and initialize the weights from a random distribution with vairiance $0.1$ and mean $0.0$.




In [1]:
# code



#### b
Instantiate the class to create a model. Access the weights and biases and print them.


In [2]:
# code

#### c

Create a tensor X with 2 samples and 3 features randomly from a uniform distribution. Suppose the labels are 0 and 1, respectively for these two samples.

In [3]:
# code

#### d
Define crossentropy. 

In [4]:
# code

#### e
Define an optimizer with stochastic gradient descent. Set the learning rate to 0.1.

In [5]:
# code

#### f
Set the gradients of the model to zero. Do backpropagation and find the jacobians of loss with respect to weights and biases in the first and second layers.

In [6]:
# code

#### g
Update the parameters.

In [ ]:
# code